name: Auto QA
run-name: ${{ github.actor }} is running automatic quality assurance
on:
  workflow_dispatch:
    inputs:
      layer_id:
        description: 'autoqa Layer ID'
        required: True
        default: 'ceea424c2f2149c38f1cb3be46653325'
      filter_sql:
        description: 'autoqa Filter'
        required: False
        defailt: '1=1'
jobs:
  check-points-basic:
    runs-on: ubuntu-latest
    environment: autoqa    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Install libkrb5-dev 
      run: sudo apt-get install -y libkrb5-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: quality assurance
      env:
        _AGIS_URL: ${{ secrets._AGIS_URL }}
        _AGIS_USER: ${{ secrets._AGIS_USER }}
        _AGIS_PW: ${{ secrets._AGIS_PW }}
        _AGIS_LAYER: ${{ github.event.inputs.layer_id }}
        _AGIS_SEL: ${{ github.event.inputs.filter_sql }}
      run: |
        scripts/autoqa.py 