name: Auto QA
run-name: ${{ github.actor }} is running automatic quality assurance
on: [push, workflow_dispatch]
  
jobs:
  check-points-basic:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Install xmllint
      run: sudo apt-get install -y libkrb5-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: quality assurance
      run: |
        scripts/autoqa.py 
   